// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mightyfin.Erp.Procurement.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mightyfin.Erp.Procurement.Infrastructure.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20261004022058_P1P3FieldCoverage")]
    partial class P1P3FieldCoverage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("procurement")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorSubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject_id");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields_json");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "RecordType", "RecordId", "CreatedAt");

                    b.ToTable("audit_events", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.BudgetCheckSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CheckedAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("checked_amount");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExchangeRateSource")
                        .HasColumnType("text")
                        .HasColumnName("exchange_rate_source");

                    b.Property<string>("FinanceCheckRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("finance_check_ref");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<string>("ReservationRef")
                        .HasColumnType("text")
                        .HasColumnName("reservation_ref");

                    b.Property<string>("ReservationStatus")
                        .HasColumnType("text")
                        .HasColumnName("reservation_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "FinanceCheckRef")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "PurchaseRequestId");

                    b.ToTable("budget_check_snapshots", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.CatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudienceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audience_code");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<Guid?>("ContractRef")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<decimal?>("MaximumQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum_quantity");

                    b.Property<decimal?>("MinimumQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_quantity");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("published_version");

                    b.Property<Guid?>("SiteRef")
                        .HasColumnType("uuid")
                        .HasColumnName("site_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TaxBasis")
                        .HasColumnType("text")
                        .HasColumnName("tax_basis");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_code");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId");

                    b.HasIndex("TenantId", "LegalEntityId", "CatalogItemId", "Status");

                    b.ToTable("catalog_entries", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_entry_values", "unit_price >= 0 AND (minimum_quantity IS NULL OR minimum_quantity >= 0) AND (maximum_quantity IS NULL OR maximum_quantity >= 0) AND (minimum_quantity IS NULL OR maximum_quantity IS NULL OR maximum_quantity >= minimum_quantity)");
                        });
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetClassRef")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_class_ref");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExpenseAccountRef")
                        .HasColumnType("text")
                        .HasColumnName("expense_account_ref");

                    b.Property<Guid?>("ImageDocumentRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_document_ref_id");

                    b.Property<bool>("InspectionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("inspection_required");

                    b.Property<Guid?>("InventoryItemRef")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_ref");

                    b.Property<bool>("IsAsset")
                        .HasColumnType("boolean")
                        .HasColumnName("is_asset");

                    b.Property<bool>("IsPurchasable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_purchasable");

                    b.Property<bool>("IsStockItem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stock_item");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_part_number");

                    b.Property<decimal?>("MinimumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_order_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PurchaseUnitCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purchase_unit_code");

                    b.Property<decimal?>("PurchaseUnitConversion")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("purchase_unit_conversion");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<Guid?>("SpecificationDocumentRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("specification_document_ref_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TaxCodeRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_code_ref");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LegalEntityId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "Status", "CategoryCode");

                    b.ToTable("catalog_items", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_item_buying_values", "(purchase_unit_conversion IS NULL OR purchase_unit_conversion > 0) AND (minimum_order_quantity IS NULL OR minimum_order_quantity >= 0) AND (lead_time_days IS NULL OR lead_time_days >= 0)");
                        });
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppliedRows")
                        .HasColumnType("integer")
                        .HasColumnName("applied_rows");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_sha256");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("record_type");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "State", "ExpiresAt");

                    b.ToTable("import_batches", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("State", "NextAttemptAt");

                    b.HasIndex("TenantId", "LegalEntityId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("outbox_events", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PolicyEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<string>("ResultCode")
                        .HasColumnType("text")
                        .HasColumnName("result_code");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "PolicyVersionId");

                    b.HasIndex("TenantId", "LegalEntityId", "PurchaseRequestId", "EvaluatedAt");

                    b.ToTable("policy_evaluations", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("policy_key");

                    b.Property<int>("PolicyVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version_number");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules_json");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LegalEntityId", "PolicyKey", "PolicyVersionNumber")
                        .IsUnique();

                    b.ToTable("policy_versions", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.ProcurementAttachmentRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_service_id");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("document_version");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("owner_type");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scan_status");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "DocumentServiceId", "DocumentVersion")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "OwnerType", "OwnerId");

                    b.ToTable("attachment_refs", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalInstanceRef")
                        .HasColumnType("text")
                        .HasColumnName("approval_instance_ref");

                    b.Property<string>("ApprovalState")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("approval_state");

                    b.Property<Guid?>("BranchRef")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_ref");

                    b.Property<string>("CostCenterRef")
                        .HasColumnType("text")
                        .HasColumnName("cost_center_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DeliveryAddressText")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address_text");

                    b.Property<string>("DeliveryLocationRef")
                        .HasColumnType("text")
                        .HasColumnName("delivery_location_ref");

                    b.Property<Guid?>("DepartmentRef")
                        .HasColumnType("uuid")
                        .HasColumnName("department_ref");

                    b.Property<string>("FundingSourceRef")
                        .HasColumnType("text")
                        .HasColumnName("funding_source_ref");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateOnly?>("NeededBy")
                        .HasColumnType("date")
                        .HasColumnName("needed_by");

                    b.Property<string>("NotesToApprover")
                        .HasColumnType("text")
                        .HasColumnName("notes_to_approver");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<string>("OnBehalfOfSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("on_behalf_of_subject_id");

                    b.Property<string>("PlanRef")
                        .HasColumnType("text")
                        .HasColumnName("plan_ref");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("text")
                        .HasColumnName("project_ref");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<Guid>("RequesterWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_worker_id");

                    b.Property<Guid?>("SiteRef")
                        .HasColumnType("uuid")
                        .HasColumnName("site_ref");

                    b.Property<string>("SourceChannel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_channel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long?>("SubmittedVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("submitted_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LegalEntityId", "Number")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "RequesterWorkerId", "Status");

                    b.ToTable("purchase_requests", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequestAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("decided_by");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("method");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<Guid>("PurchaseRequestLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_line_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "PurchaseRequestId", "PurchaseRequestLineId");

                    b.ToTable("purchase_request_allocations", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_pr_allocation_nonnegative", "quantity > 0 AND estimated_value >= 0");
                        });
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequestLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AcceptedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("accepted_quantity");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("allocated_quantity");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("approval_status");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("approved_quantity");

                    b.Property<decimal>("CancelledQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cancelled_quantity");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<string>("CostCenterRef")
                        .HasColumnType("text")
                        .HasColumnName("cost_center_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("discount_percent");

                    b.Property<string>("EstimatedCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estimated_currency_code");

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estimated_unit_price");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<DateOnly?>("NeededBy")
                        .HasColumnType("date")
                        .HasColumnName("needed_by");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid?>("PreferredSupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_supplier_id");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("text")
                        .HasColumnName("project_ref");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<string>("PurchaseType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("purchase_type");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("requested_quantity");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("route");

                    b.Property<Guid?>("SpecificationDocumentRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("specification_document_ref_id");

                    b.Property<string>("TaxCodeRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_code_ref");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "CatalogItemId");

                    b.HasIndex("TenantId", "LegalEntityId", "PreferredSupplierId");

                    b.HasIndex("TenantId", "LegalEntityId", "PurchaseRequestId", "LineNumber")
                        .IsUnique();

                    b.ToTable("purchase_request_lines", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_pr_line_nonnegative", "requested_quantity > 0 AND estimated_unit_price >= 0 AND approved_quantity >= 0 AND allocated_quantity >= 0 AND ordered_quantity >= 0 AND accepted_quantity >= 0 AND cancelled_quantity >= 0 AND (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100))");
                        });
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<string>("CompanyIdType")
                        .HasColumnType("text")
                        .HasColumnName("company_id_type");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("EligibleFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligible_from");

                    b.Property<DateTimeOffset?>("EligibleUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligible_until");

                    b.Property<string>("FinanceSupplierRef")
                        .HasColumnType("text")
                        .HasColumnName("finance_supplier_ref");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text")
                        .HasColumnName("hold_reason");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local");

                    b.Property<bool>("IsOrderable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_orderable");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred");

                    b.Property<bool>("IsStrategic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_strategic");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("NormalizedRegistration")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_registration");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<string>("PaymentTermRef")
                        .HasColumnType("text")
                        .HasColumnName("payment_term_ref");

                    b.Property<string>("PaymentVerificationCallbackRef")
                        .HasColumnType("text")
                        .HasColumnName("payment_verification_callback_ref");

                    b.Property<string>("PaymentVerificationStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("payment_verification_status");

                    b.Property<string>("PaymentVerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_verification_token");

                    b.Property<string>("PortalAccessState")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("portal_access_state");

                    b.Property<Guid?>("ProposedByWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by_worker_id");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("RiskTier")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_tier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_decided_at");

                    b.Property<string>("StatusDecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("status_decided_by");

                    b.Property<Guid?>("StatusPolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_policy_version_id");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text")
                        .HasColumnName("status_reason");

                    b.Property<string>("SupplierType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("supplier_type");

                    b.Property<string>("TaxCategoryRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_category_ref");

                    b.Property<string>("TaxIdentifierRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_identifier_ref");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradingName")
                        .HasColumnType("text")
                        .HasColumnName("trading_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LegalEntityId", "Number")
                        .IsUnique();

                    b.HasIndex("TenantId", "LegalEntityId", "Status");

                    b.HasIndex("TenantId", "LegalEntityId", "CountryCode", "NormalizedRegistration")
                        .IsUnique()
                        .HasFilter("normalized_registration IS NOT NULL");

                    b.HasIndex("TenantId", "LegalEntityId", "IsOrderable", "Status");

                    b.ToTable("suppliers", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "Kind", "FieldKey")
                        .IsUnique();

                    b.ToTable("supplier_attributes", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "CategoryCode")
                        .IsUnique();

                    b.ToTable("supplier_categories", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("text")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("text")
                        .HasColumnName("work_phone");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("is_primary = true");

                    b.ToTable("supplier_contacts", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorSubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid?>("PolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_version_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "DecidedAt");

                    b.ToTable("supplier_decisions", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("EvidenceDocumentRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_document_ref_id");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Issuer")
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("qualification_type");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "ExpiresOn");

                    b.ToTable("supplier_qualifications", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsServiceSite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_service_site");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "LegalEntityId", "Id");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "Kind");

                    b.HasIndex("TenantId", "LegalEntityId", "SupplierId", "Kind", "IsPrimary")
                        .IsUnique()
                        .HasFilter("is_primary = true");

                    b.ToTable("supplier_sites", "procurement");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.BudgetCheckSnapshot", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "PurchaseRequestId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.CatalogEntry", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.CatalogItem", null)
                        .WithMany("Entries")
                        .HasForeignKey("TenantId", "LegalEntityId", "CatalogItemId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PolicyEvaluation", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "PolicyVersionId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "PurchaseRequestId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequestAllocation", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", null)
                        .WithMany("Allocations")
                        .HasForeignKey("TenantId", "LegalEntityId", "PurchaseRequestId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PurchaseRequestLine", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "PurchaseRequestId", "PurchaseRequestLineId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "PurchaseRequestId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequestLine", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "CatalogItemId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LegalEntityId", "PreferredSupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("TenantId", "LegalEntityId", "PurchaseRequestId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierAttribute", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Attributes")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierCategory", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Categories")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierContact", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierDecision", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Decisions")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierQualification", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.SupplierSite", b =>
                {
                    b.HasOne("Mightyfin.Erp.Procurement.Domain.Supplier", null)
                        .WithMany("Sites")
                        .HasForeignKey("TenantId", "LegalEntityId", "SupplierId")
                        .HasPrincipalKey("TenantId", "LegalEntityId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.CatalogItem", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.PurchaseRequest", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Mightyfin.Erp.Procurement.Domain.Supplier", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Categories");

                    b.Navigation("Contacts");

                    b.Navigation("Decisions");

                    b.Navigation("Qualifications");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
